api/urls.py
# coding: utf-8
from __future__ import absolute_import
from __future__ import print_function
from __future__ import division
from __future__ import unicode_literals
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='api/index.html'), name="api_index"),
    url(r'^patch', views.SubmitPatch.as_view(), name="api_patch"),
    url(r'^tag/search/(?P<query>[^/]+)?$', views.tag_search_view, name="api_tag_search"),
]

debtagsd/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
import reports.views as rviews
import django.contrib.auth.views as auth_views

urlpatterns = [
    url(r'^robots.txt$', TemplateView.as_view(template_name='robots.txt', content_type="text/plain"), name="root_robots_txt"),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name="root_index"),
    url(r'^license/$', TemplateView.as_view(template_name='license.html'), name="root_license"),
    url(r'^doc/sso/$', TemplateView.as_view(template_name='doc/sso.html'), name="root_doc_sso"),
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'registration/login.html'}),
    url(r'^accounts/logout/$', auth_views.logout, {'next_page': '/'}),
    url(r'^api/', include("api.urls")),
    url(r'^rep/', include("reports.urls")),
    url(r'^reports/', include("reports.urls")),
    url(r'^exports/', include("exports.urls")),
    url(r'^edit/', include("editor.urls")),
    url(r'^search/', include("search.urls")),
    url(r'^getting-started/$', TemplateView.as_view(template_name="reports/getting-started.html"), name="getting_started"),
    url(r'^statistics/$', rviews.Stats.as_view(), name="statistics"),
]

search/urls.py
# coding: utf-8
from __future__ import absolute_import
from __future__ import print_function
from __future__ import division
from __future__ import unicode_literals
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.Search.as_view(), name="search_packages"),
]

search/models.py
# debtagsd website search and browse
#
# Copyright (C) 2012  Enrico Zini <enrico@debian.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.db import models
from django.utils.translation import ugettext_lazy as _
from backend import models as bmodels

search/views.py
from django import forms
from django.utils.translation import ugettext as _
from django.views.generic import TemplateView
from api import models as amodels


class SearchForm(forms.Form):
    q = forms.CharField(required=False, label=_("Search"))
    qf = forms.ChoiceField(required=False, label=_("Filter"), choices=[(x, y["desc"]) for x, y in amodels.FILTERS])
    wl = forms.CharField(required=False, widget=forms.HiddenInput())


class Search(TemplateView):
    template_name = "search/search.html"

    def get_context_data(self, **kw):
        ctx = super(Search, self).get_context_data(**kw)

        query = self.request.GET.get("q", None)
        res = None
        facets = None
        facets_sel = set()
        if query is None:
            form = SearchForm()
        else:
            form = SearchForm(self.request.GET)
            if form.is_valid():
                wl = set(x for x in form.cleaned_data["wl"].split(",") if x)
                res = amodels.search_query(form.cleaned_data["q"], form.cleaned_data["qf"], whitelist=wl, count_tags=20)

                # Group resulting tags by facet
                by_facet = dict()
                for t in res["tags"]:
                    by_facet.setdefault(t["tag"].facet, []).append(t)

                # Sort by short descriptions
                facets = []
                facets_rescount = []
                for facet, tags in by_facet.items():
                    has_sel = any(t["sel"] for t in tags)
                    # Take note of which facets are selected
                    if has_sel:
                        facets_sel.add(facet.name)
                    # Remove tags with too small a package number
                    tags = [t for t in tags if t["sel"] or t["w"] > 1]
                    # Skip facets with only one tag and no currently selected tags
                    if len(tags) < 2 and not has_sel:
                        continue
                    # Sort tags by short description
                    tags = sorted(tags, key=lambda x: x["tag"].sdesc)
                    facets.append((facet, tags))
                    facets_rescount.append((sum(t["w"] for t in tags), facet.name))

                # Keep only the top-5 facets with the highest number of results
                if len(facets) > 5:
                    facets_rescount.sort(reverse=True)
                    top_facets = set(x[1] for x in facets_rescount[:5])
                    facets = [(facet, tags) for facet, tags in facets if facet.name in facets_sel or facet.name in top_facets]

                facets.sort(key=lambda x: x[0].sdesc)

        ctx.update(
            form=form,
            res=res,
            facets=facets,
            has_sel=(len(facets_sel) > 0),
        )
        return ctx

search/templates/search/search.html
{% extends "debtags-base.html" %}

{% block title %}Debtags package search{% endblock %}

{% block navbar %}
{{block.super}}
<li class="nav-item">
  <a class="nav-link" href="https://wiki.debian.org/Debtags/SearchHelp">Help</a>
</li>
{% endblock %}

{% block head %}
{{block.super}}
<style type="text/css">
td.head {
    white-space: nowrap;
}

td.head span.count {
    font-weight: bold;
}

.spelling {
    cursor: pointer;
    font-weight: bold;
}

a.searchhelp {
    font-size: small;
    color: #54638c;
    text-decoration: none;
}
a.searchhelp:hover {
    text-decoration: underline;
}

#refine {
    background-color: #F5F6F7;
}
#refine li.tag {
    cursor: pointer;
}
#refine li.tag:hover {
    text-decoration: underline;
}
#refine li.tag.current .sdesc {
    font-weight: bold;
}
#refine .tagcard {
    color: gray;
}
</style>
<script type="text/javascript">
(function($) {
"use strict";

function main()
{
    $(".spelling").click(function(ev) {
        $("#id_q").val($(this).text());
        $("#search-form").submit();
    });

    $("#refine li.tag").click(function(ev) {
        var el = $(this);
        var tag = el.attr("tag");
        var wl = $("#id_wl");
        var tags = {};

        // Parse selected tags
        $.each(wl.val().split(","), function(idx, val) { if (val) tags[val] = true; });

        // Toggle this one
        if (tags[tag])
            delete tags[tag];
        else
            tags[tag] = true;

        // Set the new value
        wl.val($.map(tags, function(val, key) { return key; }).join(","));

        $("#search-form").submit();
    });

    $("#clear-tags").click(function() {
        $("#id_wl").val("");
        $("#search-form").submit();
    });
}

$(main);

})(jQuery);
</script>
{% endblock %}

{% block content %}

<h1>Package search</h1>

<div class="container-flexible">
  <div class="row">
    <div class="col">
      <form method="GET" action="{% url "search_packages" %}" id="search-form">
      {{form.wl}}
      <p>
          {{form.q.label}}: {{form.q}} {{form.qf.label}}: {{form.qf}} <input type="submit">
          <a class="searchhelp" href="https://wiki.debian.org/Debtags/SearchHelp">[help]</a>
      </p>
      </form>
      {% if res.spelling and res.spelling != res.query %}
      <p>Did you mean <span class="spelling">{{res.spelling}}</span>?</p>
      {% endif %}
    </div>
  </div>

{% if res %}
  <div class="row">
    <div class="col-3">
      <div class="card" id="refine">
        <div class="card-header">Refine search</div>

        <div class="card-body">
          {% if has_sel %}
          <p class="card-text"><a id="clear-tags" href="#" class="btn btn-primary">unselect all</a></p>
          {% endif %}

          {% for facet, tags in facets %}
          <div class="card mb-3">
            <div class="card-header">{{facet.sdesc}}</div>
            <ul class="tags list-group list-group-flush">
            {% for t in tags %}
            {% if t.sel %}
            <li class="list-group-item tag current" tag="{{t.tag.name}}"><span class="sdesc">{{t.tag.sdesc}}</span> <span class="tagcard">(remove)</span></li>
            {% else %}
            <li class="list-group-item tag" tag="{{t.tag.name}}"><span class="sdesc">{{t.tag.sdesc}}</span> <span class="tagcard">({{t.w}})</span></li>
            {% endif %}
            {% endfor %}
            </ul>
          </div>
        {% endfor %}
      </div>
      </div>
    </div>

    <div class="col-9">
      <div id="search-results">
      {% if res.match_estimated == 0 %}
      {% if res.query %}
      <p><b>No results</b> for <b>{{res.query}}</b>:</p>
      {% endif %}
      {% else %}
      <p>
        {% if res.matches|length < res.match_estimated %}
        About
        {% endif %}
        <b>{{res.match_estimated}}</b> result{{res.match_estimated|pluralize}} for <b>{{res.query}}</b>:
      </p>
      {% endif %}

      <table class="table table-striped search_results">
      {% for m in res.matches %}
      <tr>
          <td class="head">
              <span class="count">{{forloop.counter}}:</span>
              <span class="perc">{{m.perc}}%</span>
          </td>
          <td>
            {% with m.pkg as pkg %}
            {% include "debtags-pkginfo.html" with class="collapsed" %}
            {% endwith %}
          </td>
      </tr>
      {% endfor %}
      </table>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% endblock %}

{% block footer %}
{{block.super}}
<p>Powered by <a href="http://xapian.org/">Xapian</a> and <a href="http://www.enricozini.org/sw/apt-xapian-index/">apt-xapian-index</a>.</p>
{% endblock %}